# Generated by Django 4.2.1 on 2023-05-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trefwoord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Uitspraak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=24)),
                ('ecli', models.CharField(max_length=24)),
                ('samenvatting', models.TextField()),
                ('datum', models.DateField()),
                ('link', models.URLField()),
                ('inhoud', models.TextField()),
                ('trefwoorden', models.ManyToManyField(to='uitspraken.trefwoord')),
            ],
        ),
    ]
