# Generated by Django 4.2.1 on 2023-05-25 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uitspraken', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trefwoord',
            options={'verbose_name_plural': 'Trefwoorden'},
        ),
        migrations.AlterModelOptions(
            name='uitspraak',
            options={'verbose_name_plural': 'Uitspraken'},
        ),
    ]
