# Generated by Django 4.2.1 on 2023-05-30 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uitspraken', '0002_alter_trefwoord_options_alter_uitspraak_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trefwoord',
            name='type',
            field=models.CharField(max_length=24),
        ),
    ]
