# Generated by Django 4.2.1 on 2023-05-30 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uitspraken', '0003_alter_trefwoord_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trefwoord',
            old_name='name',
            new_name='naam',
        ),
    ]
