# Generated by Django 4.2.1 on 2023-06-01 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uitspraken', '0004_rename_name_trefwoord_naam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uitspraak',
            name='titel',
            field=models.CharField(max_length=100),
        ),
    ]
