# Generated by Django 4.2.1 on 2023-08-10 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uitspraken', '0005_alter_uitspraak_titel'),
    ]

    operations = [
        migrations.AddField(
            model_name='uitspraak',
            name='label',
            field=models.CharField(choices=[('NEW', 'Nieuw'), ('TRU', 'Goed'), ('FAL', 'Fout')], default='NEW', max_length=3),
        ),
        migrations.AddField(
            model_name='uitspraak',
            name='oordeel',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uitspraak',
            name='plaats',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='uitspraak',
            name='provincie',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='uitspraak',
            name='uitleg',
            field=models.CharField(default='', max_length=250),
        ),
    ]
