# Generated by Django 4.2.1 on 2023-08-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uitspraken', '0006_uitspraak_label_uitspraak_oordeel_uitspraak_plaats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uitspraak',
            name='appellant',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='uitspraak',
            name='counterpart',
            field=models.CharField(default='', max_length=250),
        ),
    ]
