# Generated by Django 4.2.11 on 2024-05-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uitspraken', '0007_uitspraak_appellant_uitspraak_counterpart'),
    ]

    operations = [
        migrations.AddField(
            model_name='uitspraak',
            name='beslissing',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='uitspraak',
            name='label',
            field=models.CharField(choices=[('NEW', 'Nieuw'), ('TRU', 'Goed'), ('FAL', 'Fout'), ('UNK', 'Weet niet')], default='NEW', max_length=3),
        ),
    ]
