# Generated by Django 4.2.11 on 2024-06-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uitspraken', '0009_letter_uitspraak_letters'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppellantType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='uitspraak',
            name='appellant_types',
            field=models.ManyToManyField(to='uitspraken.appellanttype'),
        ),
    ]
