# Generated by Django 4.2.11 on 2025-04-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uitspraken', '0010_appellanttype_uitspraak_appellant_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='uitspraak',
            name='appellant_type',
            field=models.CharField(blank=True, choices=[('BUR', 'Burger'), ('BES', 'Bestuursorgaan'), ('MIX', 'Mengsel'), ('UNK', 'Weet niet')], max_length=3, null=True),
        ),
    ]
